services:
  user-service:
    container_name: transcenders-user-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: service
      args:
        SERVICE_NAME: user-service
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    volumes:
      - user_uploads:/workspace/services/user-service/uploads
      - user_data:/workspace/services/user-service/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    container_name: transcenders-auth-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: service
      args:
        SERVICE_NAME: auth-service
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    volumes:
      - auth_data:/workspace/services/auth-service/data
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_healthy

  score-service:
    container_name: transcenders-score-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: service
      args:
        SERVICE_NAME: score-service
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - score_data:/workspace/services/score-service/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  user_uploads:
  user_data:
  auth_data:
  score_data:
