services:
  prod:
    container_name: transcenders-prod
    image: transcenders-prod:hive
    build:
      context: .
      dockerfile: services/user-service/dockerfile
      target: production
    ports:
      - "30000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
