# Base image
FROM node:24-slim AS base
WORKDIR /workspace
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
        libsqlite3-0 \
    && rm -rf /var/lib/apt/lists/*

# Development stage
FROM base AS development
RUN apt-get update && apt-get install -y --no-install-recommends \
        libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy all package.json files first
COPY package.json package-lock.json ./
COPY services/user-service/package.json ./services/user-service/
# Copy all the workspace-packages
COPY packages/ ./packages/

RUN npm ci

#copy all source files
COPY services/user-service/ ./services/user-service/

WORKDIR /workspace/services/user-service

ENV NODE_ENV=development
EXPOSE 3000 9228
CMD ["npm", "run", "dev"]

# Production stage
FROM base AS production
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
libsqlite3-dev \
&& rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
COPY packages/ ./packages/
COPY services/user-service/package.json ./services/user-service/

RUN npm ci --omit=dev

COPY services/user-service/ ./services/user-service/
RUN npm run build --workspace=user-service
COPY dist/ ./dist/

WORKDIR /workspace/services/user-service
COPY --from=build /workspace/services/user-service/dist ./dist

VOLUME ["/workspace/services/user-service/data"]
EXPOSE 3000
ENV NODE_ENV=production
CMD ["node", "dist/server.js"]
