CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY,
  winner_id INTEGER NOT NULL,
  loser_id INTEGER NOT NULL,
  winnner_score INTEGER NOT NULL,
  loser_score INTEGER NOT NULL,
  game_duration INTEGER NOT NULL,
  game_start TIMESTMP NOT NULL,
  game_end TIMESTMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);