# Base image
FROM node:22-alpine AS base
WORKDIR /workspace
USER root

# Install only SQLite runtime
RUN apk add --no-cache sqlite

# Development stage
FROM base AS development

COPY package.json package-lock.json ./
COPY services/auth-service/package.json ./services/auth-service/
# Copy all the workspace-packages
COPY packages/ ./packages/

RUN npm ci

COPY services/auth-service/ ./services/auth-service/

WORKDIR /workspace/services/auth-service

ENV NODE_ENV=development
EXPOSE 3002 9227
CMD ["npm", "run", "dev"]

# Production stage
FROM base AS production

COPY package.json package-lock.json ./
COPY packages/contracts/ ./packages/contracts/
COPY services/auth-service/package.json ./services/auth-service/

RUN npm ci --omit=dev

COPY services/auth-service/ ./services/auth-service/
RUN npm run build --workspace=auth-service

WORKDIR /workspace/services/auth-service

EXPOSE 3002
ENV NODE_ENV=production
CMD ["node", "dist/server.js"]